"""Fine-tune LegalBERT as a real sequence-classification head over the
7 CUAD-grounded clause categories (Checkpoint 4 stretch goal, PACE ICE).

Unlike `app/clauses/classifier.py`'s `LegalBertClassifier` (a zero-shot-style
classifier: embed each category's keyword description and each clause with
plain LegalBERT, then pick by cosine similarity -- no training involved),
this trains an actual `AutoModelForSequenceClassification` head on top of
`nlpaueb/legal-bert-base-uncased` via supervised cross-entropy, using the
committed `data/legalbert_finetune_train.json` /
`data/legalbert_finetune_val.json` split (generated by
`scripts/generate_finetune_dataset.py`, disjoint from
`data/cuad_sample.json` so the eventual before/after benchmark comparison
stays clean).

Local smoke test (no GPU needed, just checks the pipeline runs end-to-end):
    python -m scripts.finetune_legalbert --smoke

Real training run (on a PACE ICE GPU node -- see docs/PACE_FINETUNE.md):
    python -m scripts.finetune_legalbert

Output: a fine-tuned model saved to `models/legalbert-finetuned/` (gitignored
-- `models/` is already excluded, see .gitignore), including a `labels.json`
mapping the model's output indices back to category names, which
`app/clauses/classifier.py`'s `FineTunedLegalBertClassifier` reads at
inference time.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
TRAIN_PATH = DATA_DIR / "legalbert_finetune_train.json"
VAL_PATH = DATA_DIR / "legalbert_finetune_val.json"
MODEL_OUT_DIR = Path(__file__).resolve().parents[1] / "models" / "legalbert-finetuned"
BASE_MODEL = "nlpaueb/legal-bert-base-uncased"


def load_records(path: Path, limit: int | None = None) -> list[dict]:
    records = json.loads(path.read_text())
    return records[:limit] if limit else records


def build_label_list(train_records: list[dict], val_records: list[dict]) -> list[str]:
    categories = sorted({r["category"] for r in train_records + val_records})
    return categories


def run(smoke: bool, epochs: int, batch_size: int, lr: float) -> None:
    import torch
    from torch.utils.data import Dataset
    from transformers import (
        AutoModelForSequenceClassification,
        AutoTokenizer,
        Trainer,
        TrainingArguments,
    )

    limit = 24 if smoke else None  # smoke: tiny slice, just prove the pipeline runs
    train_records = load_records(TRAIN_PATH, limit=limit)
    val_records = load_records(VAL_PATH, limit=8 if smoke else None)

    labels = build_label_list(train_records, val_records)
    label_to_id = {label: i for i, label in enumerate(labels)}
    print(f"Categories ({len(labels)}): {labels}")
    print(f"Train examples: {len(train_records)}, val examples: {len(val_records)}")

    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

    class ClauseDataset(Dataset):
        def __init__(self, records: list[dict]) -> None:
            texts = [r["clause_text"] for r in records]
            self.encodings = tokenizer(
                texts, truncation=True, padding="max_length", max_length=256
            )
            self.labels = [label_to_id[r["category"]] for r in records]

        def __len__(self) -> int:
            return len(self.labels)

        def __getitem__(self, idx: int) -> dict:
            item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
            item["labels"] = torch.tensor(self.labels[idx])
            return item

    train_dataset = ClauseDataset(train_records)
    val_dataset = ClauseDataset(val_records)

    id2label = {i: label for i, label in enumerate(labels)}
    label2id = {label: i for i, label in enumerate(labels)}
    model = AutoModelForSequenceClassification.from_pretrained(
        BASE_MODEL, num_labels=len(labels), id2label=id2label, label2id=label2id
    )

    def compute_metrics(eval_pred) -> dict:
        from sklearn.metrics import precision_recall_fscore_support

        predictions, label_ids = eval_pred
        preds = predictions.argmax(axis=-1)
        precision, recall, f1, _ = precision_recall_fscore_support(
            label_ids, preds, average="macro", zero_division=0
        )
        return {"macro_precision": precision, "macro_recall": recall, "macro_f1": f1}

    training_args = TrainingArguments(
        output_dir=str(MODEL_OUT_DIR / "checkpoints"),
        num_train_epochs=1 if smoke else epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        learning_rate=lr,
        eval_strategy="epoch",
        save_strategy="no",  # only the final save_pretrained below is kept
        logging_steps=5,
        report_to=[],
        fp16=torch.cuda.is_available(),
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    metrics = trainer.evaluate()
    print("Final eval metrics:", metrics)

    final_dir = MODEL_OUT_DIR / "final"
    final_dir.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(final_dir)
    tokenizer.save_pretrained(final_dir)
    (final_dir / "labels.json").write_text(json.dumps(labels, indent=2))
    (final_dir / "eval_metrics.json").write_text(json.dumps(metrics, indent=2))
    print(f"Saved fine-tuned model to {final_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--smoke", action="store_true",
        help="Tiny run (24 train / 8 val examples, 1 epoch) to verify the pipeline works, no GPU required.",
    )
    parser.add_argument("--epochs", type=int, default=6)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=2e-5)
    args = parser.parse_args()
    run(smoke=args.smoke, epochs=args.epochs, batch_size=args.batch_size, lr=args.lr)


if __name__ == "__main__":
    main()
